;
; 1.asm
;
; Created: 05-Mar-19 8:12:57 PM
; Author : Edward Omondi
;


		.INCLUDE "M32DEF.INC" ;THE DEFINITION FILE
		.ORG 0x0000

		LDI R16, 0xFF ;loading output to r16
		OUT DDRB, R16 ;data in r16 is to be 'outputed' at port b

		LDI ZH, HIGH(MYDATA<<1) ;loading highbits in my data to zh 
		LDI ZL, LOW(MYDATA<<1) ;loading low bits in my data to zl

LOOP1:	LPM R20, Z+ /*Z+ SHOWS WE ARE AUTOMATICALLY INCREASING THE ADDRESS OF
						 WHERE THE DATA IS STORED*/
		CPI R20, 0 ;COMPARE DATA IN R20 TO 0 THAT IS IN THE DATA SYSTEM
		BREQ END /*IF DATA ABOVE IS EQUAL TO 0, THEN GO TO END
					IF NOT, IT WILL CONTINUE READING THE DATA AND 
					CONTINUE SENDING OUTPUT TO PORT B*/
		OUT PORTB, R20 ;HERE R20 DATA IS SENT TO PORT B
		RJMP LOOP1
					


END:	RJMP END

		.ORG 0x500 ;WHERE THE DATA IS LOCATED

MYDATA: .DB "HELLO WORLD", 0 ;THE DATA IN THE SYSTEM